### ISSUE TITLE
Cant make it work

### ISSUE THREAD

**Issue by shaeon** [LimeProgramming/USB-serial-mouse-adapter#1]
First of all, thank you for the project, I think it's amazing.

I had order some boards from China with the components and the rest of things I bought by internet without problems. 

The first problem was that in the readme there is no documentation about the soldering point to choose 3.3V or 5V.  Looking at the schematic and some pictures I thought I should connect 5V to the center pin. That finally let me access to serial terminal.

The problem is that I can't get the mouse to work. I have tried on modern and old computers, Even I got a db9 serial mouse that works in all computers but the usb-serial-mouser-adapter doesn't work.

The only thing was that the first time I plugged it without the soldering point, but I don't think it was damaged or anything. Maybe I'm wrong and need to solder to the 3.3V and I fried a pi pico.

I did the following test, I opened a terminal with my real serial mouse and at the top when I move the mouse I get information (strange chars mark with red line). If I swap real mouse to the usb-to-serial converter (powered by a wall charger) I get nothing on screen, but if I invoke the menu it does come up.

![imagen](https://user-images.githubusercontent.com/10370710/198065307-8f30b7e0-0ea2-42ac-beb7-d948a9f80113.png)

What could it be?

**Comment by LimeProgramming** [comment]
Ah, I had to re-read the read-me. I must have completely forgotten about the jumper. 

It was very much just an early idea that stuck around. The jumper is for the max232. If you're using a max3232 then you bridge 3.3v to the center pin and bridge R4 and R3, and remove R1 and R2 (This was my first real PCB and it made sense to me at the time to do it that way) 
If you're using a max232 then you bridge 5v to the center pin and install all the resistors. 

I made it that way because technically using a max232 is out of spec and it should use a max3232 however the max3232 costs more, is potentially less compatible with host machines. and the basic part and cheaper max232 from JLC works just fine and is within tolerances. 

Due to changes in the firmware the ALRT LED is really a mouse LED. It should light up when a usb mouse in connected to it. If it doesn't that means something else is on the USB line. In testing with others, usb wall power bricks connected to the microusb port can stop the pico from picking up the mouse. 

You can solve this by a few ways:
- Using a USB brick that doesn't have data connections 
- Using a USB cable that doesn't have data connections, (mine didn't, it was supposed to but it seems that they were broken) IF you're feeling up for it, you can cut into a usb cable gently and just cut the white and blue wires inside it. Sometimes really cheap ones for charging phones lack the data lines.
- Powering it via the pin headers. 

I also believe that you can use an USB OTG with the extra connection for power. I believe so, I haven't used one myself. 
 
 
Sorry about that. I never thought at the time about this issue. I have been working on a new edition of this board that's powered differently to fix this issues. I just never backported it since I didn't think people were interested in this project. 

Also, those weird characters on top of putty print out, that's just the mouse movement data. It;s what your driver usually see's

I hope that helps. 
If you're interested, there is a thread on vogons about this project that might help. I've documented a lot there while working on this, if something is missing from the readme here, it would be somewhere there.
https://www.vogons.org/viewtopic.php?f=46&t=84280

-Lime

**Comment by shaeon** [comment]
I did order to JLC with your gerbers, bom list, all! It was so easy :)

4 person (some friends) ask me about this adapter, because the serial mouse became be so difficult to get. I discovery what's wrong looking scheme and photos at vogons.org web.

![imagen](https://user-images.githubusercontent.com/10370710/198308983-f1b61735-1f36-4c4e-9c67-b92612e23315.png)


I didn't solder wires between usb D+ D- line from pcb to pi pico. Again i didn't read that on readme. I'll test it tomorrow because because I have board at work. I'll tell you them.

Thanks for your help / support. :)

**Comment by LimeProgramming** [comment]
Wow I forgot about those wires myself. 

I'm going to have to update the read me with an assembly section. 
Again, Sorry about that. I also have a firmware update that I have to push out but I'm messing with drivers at the moment. You might have read on Vogons that I want to get higher baud rates working on win95, I don't know how possible that actually is though but we'll see. There has also been an update to TinyUSB and it behaves much nicer with hubs and multiple devices present (most of the time anyway)

You just have to solder TP2 on the PCB to TP2 of the pico, TP3 of the PCB to TP3 of the pico. 


Let me know what you use this for, I'm very curious what people would want these for. 
-Lime

**Comment by shaeon** [comment]
Hi Lime!

I solder the two D-,D+ usb lines but i cant still make it works. I think i'm loosing something. Even I tried do nuked and after load again firmware 1.3.2. Maybe i need try another version?

I tried: Two different boards with 3 different usb mouses, in 3 different computer, but i cant get light in "alarm" light when i plug mouse, so I think this is the big problem. 

My boards come with almost solders from JLC (even cheap max232). I just got your gerbers and bom and upload. I test line from usb with tester and i have line in pinheader J3, 5V and GND. 

What i can test it more?

We'll use in old computer, because old serial mouse became more hard to make it work. 

Best Regards.

**Comment by LimeProgramming** [comment]
I tried nuking one of my boards, loaded the firmware 1.3.2, plugged in a usb mouse and it worked. 
I cut open the usb cable to cut the white and green wires for reasons I said in my first reply. 

You are getting a power LED aswell yeah? it's not a case of just soldering in the leds the wrong way. The power led comes on when the device has power and it blinks to tell you it's in serial terminal mode. 

![IMG_20221102_162657177](https://user-images.githubusercontent.com/29736217/199547061-edb8667c-01fd-474e-878a-d58710af3922.jpg)

**Comment by LimeProgramming** [comment]
As you can see, the ARLT led lit up without the serial port being connected to anything. 

The mouse is a standard microsoft mouse and this adapter has worked with every usb mouse I tried. 


Does this image help at all? 

You can ignore the black jumper above the green led, I didn't notice it before taking the picture. It's not doing anything.

**Comment by shaeon** [comment]
I did a lot of test, i think maybe my wire is thin but change mouse (one that work on mist) and power by duponts work perfect! :)

I'm sorry be so late answer you. Thanks for your support.

I close this issue. (very happy!)
