### ISSUE TITLE
LCSC / JLCPBC parts

### ISSUE THREAD

**Issue by sweetlilmre** [LimeProgramming/USB-serial-mouse-adapter#4]
In #2 a user is asking for the complete BOM list, specifically required is the DB9, dip switch block, USB A socket.
Could you provide these? A full BOM with everything: LEDs etc would be appreciated.
I have looked at LCSC and found these part numbers which may work:

DB9: C141882
DIP Block: C5299507
USB Socket: C720524

**Comment by LimeProgramming** [comment]
Parts your picked should work fine, but here's what I used.

DIP 9: C141882
USB socket: C26235
Dip block: C962227

LED's are LED's, pick your favourite colors and enjoy.

I feel like this project has gotten far more interest than I thought it would, especially in the last 2 or 3 weeks. Did something happen?

**Comment by sweetlilmre** [comment]
Thanks for the confirmation. I ordered the parts I'd selected, so I'm glad to know they'll work!
As far as interest, I found the project after making some of necroware's PS2 to serial adapters and trying to improve the firmware by looking at other code. I have a feeling your project might have been mentioned on the PicoGUS discord some time back but can't be sure, so that might have spurred interest. At any rate, it's an awesome solution and I can't wait to build some boards, thank you!

**Comment by LimeProgramming** [comment]
Ah I see. 

fair enough so. Good luck with them. TinyUSB at least last I looked at it was a buggy mess, so the adapter is very picky with hubs and it doesn't like unplugging and replugging the usb mouse. 

But it does work when it's working. 

I did include modified serial mouse drivers for DOS in the repo, thought I had included the modded drivers for windows 9x as well but doesn't seem like I have, no idea where those have gone now. I remember trying to make a bootdisk that installed the drivers automatically and it worked fine for english installs but no other languages because it tried to find the version of windows you were using from the license file. 

Still, thanks for the interest and enjoy.
